export const SERVICES_LIST = [
  { name: "Accounting & Financial Management", tags: ["Bookkeeping", "Virtual CFO", "MIS Reporting", "Accounting Outsourcing", "Financial Statements"], img: "/images/services/final/accounting.png", url: "/services/accounting-financial-management", description: "Integrated accounting, reporting and finance operations support\u2014from books and working capital to management reporting and financial statements." },
  { name: "Direct Taxation", tags: ["Income Tax", "Tax Planning", "TDS / TCS", "Transfer Pricing", "International Tax"], img: "/images/services/final/tax.png", url: "/services/direct-taxation", description: "Direct tax compliance and advisory for individuals and businesses, including planning, transfer pricing, cross-border taxation and assessment support." },
  { name: "Indirect Taxation (GST & Customs)", tags: ["GST Compliance", "ITC Reconciliation", "GST Reviews", "Customs", "SEZ / EOU"], img: "/images/services/final/international-finance.png", url: "/services/gst-customs", description: "End-to-end GST and indirect tax support covering registrations, returns, reconciliations, exports, customs and regulatory compliance." },
  { name: "Litigation & Regulatory Defense", tags: ["Notices", "Assessments", "Appeals", "GST Defense", "Risk Strategy"], img: "/images/services/final/legal.png", url: "#contact", description: "Strategic support for tax and regulatory disputes, notices, assessments, appeals, proceedings and pre-litigation risk evaluation." },
  { name: "Business Setups & Incorporation", tags: ["Incorporation", "FDI", "India Entry", "Startup India", "Restructuring"], img: "/images/services/final/business-setup.png", url: "/services/business-setup-incorporation", description: "Business formation and structuring support for domestic and international entrepreneurs, investors, subsidiaries and growing enterprises." },
  { name: "Secretarial & Corporate Governance", tags: ["ROC Filings", "Board Matters", "Share Capital", "DIN / KYC", "Governance"], img: "/images/services/final/legal.png", url: "/services/secretarial-corporate-governance", description: "Corporate secretarial and governance support across recurring ROC compliance, board processes, statutory records and capital changes." },
  { name: "Licenses & Regulatory Filings", tags: ["IEC", "FSSAI", "PF / ESIC / PT", "IPR", "FEMA / RBI"], img: "/images/services/final/payroll-compliance.png", url: "#contact", description: "Coordinated support for business registrations, licences and regulatory filings including FEMA, RBI, labour and intellectual property matters." },
  { name: "Financial Advisory & Corporate Finance", tags: ["Project Finance", "DPR & Models", "Valuation", "Due Diligence", "Working Capital"], img: "/images/services/final/international-finance.png", url: "/services/financial-advisory-corporate-finance", description: "Decision-focused corporate finance support covering funding, financial modelling, valuations, due diligence, controls and cash-flow optimization." },
];